### ISSUE TITLE
lots of redirect errors

### ISSUE THREAD

**Issue by chovy** [brozeph/node-craigslist#17]
```

Error: maximum redirect limit exceeded
{ host: 'vancouver.craigslist.org',
     method: 'GET',
     path: '//vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/search/sss?sort=rel&query=xbox',
     pathname: '//vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/search/sss',
     rawStream: false,
     secure: true },
```

It appears to be on only some domains not all.

**Comment by brozeph** [comment]
@chovy, thank you for the issue report. This is reproduced and now I have a test to validate that when `baseHost` is omitted for cities that are in both the US and another country (i.e. Vancouver, WA, USA vs. Vancouver, BC), the redirect limit is exceeded. Issue assigned and in progress.

```
  craigslist setting request options: { hostname: 'vancouver.craigslist.org', path: '/search/sss?sort=rel&query=xbox', secure: true } +1ms
  craigslist request options set to: { hostname: 'vancouver.craigslist.org', path: '/search/sss?sort=rel&query=xbox', secure: true } +0ms
  craigslist performing GET ({ hostname: 'vancouver.craigslist.org', path: '/search/sss?sort=rel&query=xbox', secure: true }) +0ms
  craigslist request hostname will be set to vancouver.craigslist.org (options = vancouver.craigslist.org, settings = undefined) +0ms
  craigslist request path will be set to /search/sss?sort=rel&query=xbox (options = /search/sss?sort=rel&query=xbox, settings = undefined) +1ms
  craigslist request secure will be set to true (options = true, settings = undefined) +0ms
  craigslist establishing request with options: { hostname: 'vancouver.craigslist.org', path: '/search/sss?sort=rel&query=xbox', secure: true, maxRetries: 3, rawStream: false, timeout: 30000, method: 'GET', headers: { 'Content-Length': 0 } } +0ms
  craigslist setting timeout value to 30000 +2ms
  craigslist establishing request with options: { host: 'vancouver.craigslist.org', method: 'GET', path: '//vancouver.craigslist.ca/search/sss?sort=rel&query=xbox', pathname: '//vancouver.craigslist.ca/search/sss', rawStream: false, secure: true } +476ms
  craigslist establishing request with options: { host: 'vancouver.craigslist.org', method: 'GET', path: '//vancouver.craigslist.ca/vancouver.craigslist.ca/search/sss?sort=rel&query=xbox', pathname: '//vancouver.craigslist.ca/vancouver.craigslist.ca/search/sss', rawStream: false, secure: true } +931ms
  craigslist establishing request with options: { host: 'vancouver.craigslist.org', method: 'GET', path: '//vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/search/sss?sort=rel&query=xbox', pathname: '//vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/search/sss', rawStream: false, secure: true } +693ms
  craigslist establishing request with options: { host: 'vancouver.craigslist.org', method: 'GET', path: '//vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/search/sss?sort=rel&query=xbox', pathname: '//vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/search/sss', rawStream: false, secure: true } +656ms
  craigslist establishing request with options: { host: 'vancouver.craigslist.org', method: 'GET', path: '//vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/search/sss?sort=rel&query=xbox', pathname: '//vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/search/sss', rawStream: false, secure: true } +844ms
  craigslist error: exceeded max number of redirects: { Error: maximum redirect limit exceeded at ClientRequest.<anonymous> (/source/web.js:183:18) at ClientRequest.g (events.js:291:16) at emitOne (events.js:96:13) at ClientRequest.emit (events.js:188:7) at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21) at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23) at TLSSocket.socketOnData (_http_client.js:363:20) at emitOne (events.js:96:13) at TLSSocket.emit (events.js:188:7) at readableAddChunk (_stream_readable.js:176:18) options: { host: 'vancouver.craigslist.org', method: 'GET', path: '//vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/search/sss?sort=rel&query=xbox', pathname: '//vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/search/sss', rawStream: false, secure: true }, response: { headers: { connection: 'close', 'last-modified': 'Mon, 13 Mar 2017 15:26:59 GMT', location: '//vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/vancouver.craigslist.ca/search/sss?sort=rel&query=xbox', date: 'Mon, 13 Mar 2017 15:26:59 GMT', vary: 'Accept-Encoding', 'content-length': '1', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'text/html; charset=iso-8859-1', 'set-cookie': [Object], server: 'Apache', 'strict-transport-security': 'max-age=86400; includeSubDomains' }, statusCode: 302 } } +967ms
      1) should properly search another country
```
