### ISSUE TITLE
HTTP error received: This IP has been automatically blocked

### ISSUE THREAD

**Issue by jtara1** [brozeph/node-craigslist#50]
I'm getting a 400 or higher status code on my call to list(options) method

```
node:2037) UnhandledPromiseRejectionWarning: Error: HTTP error received
    at IncomingMessage.<anonymous> (/Users/j/PersonalProjects/node_modules/reqlib/dist/index.js:515:29)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:2037) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2037) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Process finished with exit code 0

```

**Comment by brozeph** [comment]
@jtara1, can you modify your code to catch the error and then include the message on this issue?

**Comment by jtara1** [comment]
```
{ Error: HTTP error received
    at IncomingMessage.<anonymous> (/Users/j/PersonalProjects/node_modules/reqlib/dist/index.js:515:29)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  body:
   'This IP has been automatically blocked.\nIf you have questions, please email: blocks-b1557181822816873@craigslist.org\n',
  options:
   { hostname: 'losangeles.craigslist.org',
     method: 'GET',
     path:
      '/search/cta?sort=rel&bundleDuplicates=1&hasPic=1&min_price=1000&max_price=20000&min_auto_year=2010&max_auto_miles=76000&search_distance=50&searchNearby=1',
     maxRedirectCount: 5,
     maxRetryCount: 3,
     timeout: 60000,
     headers: { 'Content-Type': 'application/json', 'Content-Length': 0 },
     protocol: 'https:',
     slashes: true,
     auth: null,
     host: 'losangeles.craigslist.org',
     port: null,
     hash: null,
     search:
      '?sort=rel&bundleDuplicates=1&hasPic=1&min_price=1000&max_price=20000&min_auto_year=2010&max_auto_miles=76000&search_distance=50&searchNearby=1',
     query:
      'sort=rel&bundleDuplicates=1&hasPic=1&min_price=1000&max_price=20000&min_auto_year=2010&max_auto_miles=76000&search_distance=50&searchNearby=1',
     pathname: '/search/cta',
     href:
      'https://losangeles.craigslist.org/search/cta?sort=rel&bundleDuplicates=1&hasPic=1&min_price=1000&max_price=20000&min_auto_year=2010&max_auto_miles=76000&search_distance=50&searchNearby=1' },
  state:
   { data: '',
     failover: { index: 0, values: [] },
     redirects: [ [Url] ],
     tries: 1,
     headers:
      { 'content-length': '117',
        'set-cookie': [Array],
        'strict-transport-security': 'max-age=63072000' },
     statusCode: 403 },
  statusCode: 403 }
```

**Comment by brozeph** [comment]
Closing as duplicate to #45
